// Generated by src/cli/prepare-native.ts from the production providers/github source bundle.
// Regenerate this digest whenever the manifest or provider implementation changes.
export const GITHUB_BUILTIN_SOURCE_SHA256 =
  "60403c9e1cb43f48591015950bec12fd8e30eee972a837d3c5d1f7fc3096dd17";

export const GITHUB_BUILTIN_ARTIFACT = new TextEncoder().encode(
  `polici.github.provider-source/v1\nsha256=${GITHUB_BUILTIN_SOURCE_SHA256}\n`,
);
