// @ts-ignore The repository intentionally does not depend on @types/node.
import { createHash } from "node:crypto";
// @ts-ignore The repository intentionally does not depend on @types/node.
import { readFileSync, readdirSync } from "node:fs";
// @ts-ignore The repository intentionally does not depend on @types/node.
import { resolve } from "node:path";

export function githubArtifactModule(repositoryRoot: string): string {
  const directory = resolve(repositoryRoot, "providers/github");
  const files = readdirSync(directory)
    .filter(
      (name) =>
        name === "manifest.json" ||
        (name.endsWith(".ts") &&
          !name.endsWith(".test.ts") &&
          name !== "github-provider-native.ts"),
    )
    .sort();
  const hash = createHash("sha256");
  hash.update("polici.github.provider-source/v1\0");
  for (const name of files) {
    const relative = `providers/github/${name}`;
    const bytes = readFileSync(resolve(directory, name));
    hash.update(`${relative}\0${bytes.length}\0`);
    hash.update(bytes);
  }
  const digest = hash.digest("hex");
  return `// Generated by src/cli/prepare-native.ts from the production providers/github source bundle.
// Regenerate this digest whenever the manifest or provider implementation changes.
export const GITHUB_BUILTIN_SOURCE_SHA256 =
  "${digest}";

export const GITHUB_BUILTIN_ARTIFACT = new TextEncoder().encode(
  \`polici.github.provider-source/v1\\nsha256=\${GITHUB_BUILTIN_SOURCE_SHA256}\\n\`,
);
`;
}
